### ISSUE TITLE
Support for new region "Taiwan"

### ISSUE THREAD

**Issue by kuanting0580** [tomekkleszcz/homebridge-electrolux-devices#45] opened 2024-03-10 06:16 UTC
There are only five regions supported on the list. I tried to select these regions trying to login, but it does not work. 
Here is the log.
[3/10/2024, 2:14:38 PM] [homebridge-electrolux-devices] Signing in to Gigya...
[3/10/2024, 2:14:38 PM] [homebridge-electrolux-devices] Polling error:  Couldn't not sign in to Electrolux: Gigya API accounts.login failed with error code 301001 and message This API key is served by another data center.

Hope it will be supported for other regions.

**Comment by tomekkleszcz** [comment] 2024-03-10 13:45
@kuanting0580 Hi! Thanks for reporting the issue, I'll take a closer look at it and update you as soon as I release the fix.

**Comment by kuanting0580** [comment] 2024-03-10 13:48
@tomekkleszcz Hi!! Sure. Thanks for replying!!

**Comment by tomekkleszcz** [comment] 2024-03-10 14:42
@kuanting0580 The new version (0.0.10) has been released, please update the plugin and let me know if that works for you, so I can close this issue.

**Comment by kuanting0580** [comment] 2024-03-10 15:28
I have updated to the new version. But it is still not working. 

[3/10/2024, 11:19:25 PM] [homebridge-electrolux-devices] Signing in to Gigya...
[3/10/2024, 11:19:26 PM] [homebridge-electrolux-devices] Couldn't not sign in to Electrolux: Gigya API accounts.login failed with error code 403042 and message invalid loginID or password
[3/10/2024, 11:20:27 PM] [homebridge-electrolux-devices] Polling error:  connect EHOSTUNREACH 18.194.71.38:443
[3/10/2024, 11:20:58 PM] [homebridge-electrolux-devices] Signing in to Gigya...
[3/10/2024, 11:20:59 PM] [homebridge-electrolux-devices] Polling error:  Couldn't not sign in to Electrolux: Gigya API accounts.login failed with error code 403042 and message invalid loginID or password
[3/10/2024, 11:21:00 PM] [homebridge-electrolux-devices] Signing in to Gigya...
[3/10/2024, 11:21:01 PM] [homebridge-electrolux-devices] Polling error:  Couldn't not sign in to Electrolux: Gigya API accounts.login failed with error code 403042 and message invalid loginID or password
[3/10/2024, 11:21:28 PM] [homebridge-electrolux-devices] Signing in to Gigya...
[3/10/2024, 11:21:29 PM] [homebridge-electrolux-devices] Polling error:  Couldn't not sign in to Electrolux: Gigya API accounts.login failed with error code 403042 and message invalid loginID or password
[3/10/2024, 11:21:58 PM] [homebridge-electrolux-devices] Signing in to Gigya...
[3/10/2024, 11:21:59 PM] [homebridge-electrolux-devices] Polling error:  Couldn't not sign in to Electrolux: Gigya API accounts.login failed with error code 403120 and message Account temporarily locked out
[3/10/2024, 11:22:28 PM] [homebridge-electrolux-devices] Signing in to Gigya...
[3/10/2024, 11:22:29 PM] [homebridge-electrolux-devices] Polling error:  Couldn't not sign in to Electrolux: Gigya API accounts.login failed with error code 403120 and message Account temporarily locked out
[3/10/2024, 11:22:58 PM] [homebridge-electrolux-devices] Signing in to Gigya...
[3/10/2024, 11:22:59 PM] [homebridge-electrolux-devices] Polling error:  Couldn't not sign in to Electrolux: Gigya API accounts.login failed with error code 403120 and message Account temporarily locked out
[3/10/2024, 11:23:28 PM] [homebridge-electrolux-devices] Signing in to Gigya...
[3/10/2024, 11:23:29 PM] [homebridge-electrolux-devices] Polling error:  Couldn't not sign in to Electrolux: Gigya API accounts.login failed with error code 403120 and message Account temporarily locked out
[3/10/2024, 11:23:58 PM] [homebridge-electrolux-devices] Signing in to Gigya...
[3/10/2024, 11:23:59 PM] [homebridge-electrolux-devices] Polling error:  Couldn't not sign in to Electrolux: Gigya API accounts.login failed with error code 403120 and message Account temporarily locked out
[3/10/2024, 11:24:27 PM] [homebridge-electrolux-devices] Signing in to Gigya...
[3/10/2024, 11:24:28 PM] [homebridge-electrolux-devices] Polling error:  Couldn't not sign in to Electrolux: Gigya API accounts.login failed with error code 403120 and message Account temporarily locked out
[3/10/2024, 11:24:57 PM] [homebridge-electrolux-devices] Signing in to Gigya...
[3/10/2024, 11:24:58 PM] [homebridge-electrolux-devices] Polling error:  Couldn't not sign in to Electrolux: Gigya API accounts.login failed with error code 403120 and message Account temporarily locked out
[3/10/2024, 11:25:06 PM] [homebridge-electrolux-devices] Stopping child bridge (will not restart)...
[3/10/2024, 11:25:06 PM] Got SIGTERM, shutting down child bridge process...
[3/10/2024, 11:25:11 PM] [homebridge-electrolux-devices] Child bridge process ended

**Comment by tomekkleszcz** [comment] 2024-03-10 15:33
@kuanting0580 Are you sure you've provided a correct email and password in the config? This line indicate you configured the plugin wrong way.
`[3/10/2024, 11:19:26 PM] [homebridge-electrolux-devices] Couldn't not sign in to Electrolux: Gigya API accounts.login failed with error code 403042 and message invalid loginID or password`

**Comment by kuanting0580** [comment] 2024-03-10 15:43
I am sure that I provided the correct email address and password on the Homebridge Electrolux Devices setting page. Is there any other setting I should configure?

**Comment by kuanting0580** [comment] 2024-03-10 15:47
I leave JSON config as default.

{
    "email": **********@gmail.com",
    "password": "**********",
    "pollingInterval": 30,
    "carbonDioxideSensorAlarmValue": 1000,
    "vocMolecularWeight": 30.026,
    "_bridge": {
        "username": "0E:F4:5F:1C:35:D6",
        "port": 58822
    },
    "platform": "HomebridgeElectroluxDevices"
}

**Comment by tomekkleszcz** [comment] 2024-03-10 15:49
Are you able to login with these credentials in the Electrolux (https://apps.apple.com/pl/app/electrolux/id1595816832) app? I'm running the plugin without any issues on my Homebridge instance, so I think the issue is with your configuration.

**Comment by kuanting0580** [comment] 2024-03-10 15:53
Yes, I am able to login with my email address and passoword in this app. And I also tried to log out and login again to make sure I enter the correct credentails.

**Comment by kuanting0580** [comment] 2024-03-10 15:55
Would you mind sending my credentails to your email "tomekkleszcz[at]icloud.com"? I will change my password to a new one first. Hope it would be help.

**Comment by tomekkleszcz** [comment] 2024-03-10 16:26
> Would you mind sending my credentails to your email "tomekkleszcz[at]icloud.com"? I will change my password to a new one first. Hope it would be help.

Sure, send me your credentials and I'll check what's going on. Thanks!

**Comment by tomekkleszcz** [comment] 2024-03-10 16:51
@kuanting0580 Thank you for sending me your credentials. I'll push the fix soon. Would you mind not changing your password? I found one unsupported device and I would like to implement support for it in this plugin.

**Comment by kuanting0580** [comment] 2024-03-10 16:54
> @kuanting0580 Thank you for sending me your credentials. I'll push the fix soon. Would you mind not changing your password? I found one unsupported device and I would like to implement support for it in this plugin.

Yes, sure!!

**Comment by tomekkleszcz** [comment] 2024-03-10 17:04
> > @kuanting0580 Thank you for sending me your credentials. I'll push the fix soon. Would you mind not changing your password? I found one unsupported device and I would like to implement support for it in this plugin.
> 
> Yes, sure!!

Thanks! Just to make sure, you own PURE A9 and Jishi Home 500 (https://www.electrolux.com.tw/appliances/air-purifiers/ep53-48swa/#/)? The second device has no support yet and it's not available in Europe, but I want to confirm its name before adding it to the list.

**Comment by kuanting0580** [comment] 2024-03-10 17:14
Yes, one is PURE A9, the other one Electrolux named 500UV in Taiwan. The product link you provided is correct.
I also found the same product on Youtube which is Australian version. (https://www.youtube.com/watch?v=rAJQIjfVNYA&ab_channel=ElectroluxAu) So the offical English name of this one is UltimateHome 500.

**Closed** 2024-03-10 17:30 UTC
Labels: bug

**Comment by tomekkleszcz** [comment] 2024-03-10 17:36
@kuanting0580 The login issue and support for 500UV Air Purifier are implemented in the new 0.1.1 release.

**Comment by tomekkleszcz** [comment] 2024-03-11 09:18
@kuanting0580 The Homekit does not support showing PM1 value, the CO2 value is read from the ECO2 field (which stands for Estimated CO2 I suppose). You can increase the `carbonDioxideSensorAlarmValue` config field value to higher level for alarm not to be switched on.

**Comment by kuanting0580** [comment] 2024-03-11 13:33
Hi, thanks for your explanation!! That's why CO2 value fluctuates, so I suppose the value is inaccurated. And thanks for the advice. It works!
